services:
    rundeck:
        image: stokori:rundeck-ansible
        restart: unless-stopped
        links:
          - postgres
        environment:
            RUNDECK_DATABASE_DRIVER: org.postgresql.Driver
            RUNDECK_DATABASE_USERNAME: rundeck
            RUNDECK_DATABASE_PASSWORD: ${DB_PASS}
            RUNDECK_DATABASE_URL: jdbc:postgresql://postgres/rundeck?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
            RUNDECK_GRAILS_URL: ${GRAILS_URL}
        volumes:
          - ${RUNDECK_LICENSE_FILE:-/dev/null}:/home/rundeck/etc/rundeckpro-license.key
          - ./data:${HOME}/data
        ports:
          - 127.0.0.1:4440:4440
    postgres:
        image: postgres
        restart: unless-stopped
        expose:
          - 5432
        environment:
          - POSTGRES_DB=rundeck
          - POSTGRES_USER=rundeck
          - POSTGRES_PASSWORD=${DB_PASS}
        volumes:
          - dbdata:/var/lib/postgresql/data
    tunnel:
      container_name: cloudflared-tunnel
      image: cloudflare/cloudflared
      restart: unless-stopped
      command: tunnel run
      environment:
        - TUNNEL_TOKEN=${TUNNEL_TOKEN}

networks:
    default:
        name: tunnel

volumes:
    dbdata: